### ISSUE TITLE
feature request: ability to specify artist - title as a shorthand

### ISSUE THREAD

**Issue by sergueif** [nichobi/beets-yapl#3]
It's too tedious to always type 
```
tracks:
  - artist: foo
    title: bar
```
yaml blob

how about if the `tracks[]` entry is a single string, then some shorthand format is interpreted like `<artist> - <title>`?
e.g.:
```
name: Christmas
tracks:
  - artist: Withered Hand
    title: Real Snow
  - Withered Hand - It's a Wonderful Life
  - U.N.P.O.C. - Icelandic Leopard Cat
  - ...
```
